### ISSUE TITLE
Running SRH on bare metal alongside Redis 

### ISSUE THREAD

**Issue by niks3089** [hiett/serverless-redis-http#29] opened 2024-05-14 03:08 UTC
Is it possible to run SRH as a standalone binary outside of docker on the same server as Redis? This would be for intensive workloads which require a lot of resources so probably would be better to run outside of docker.

**Comment by hiett** [comment] 2024-05-14 03:12
This isn't something I have the bandwidth to ship (precompiled binaries), however, it should be easy to compile this project into a binary for your operating system, you can use the Dockerfile as a reference on how to get the mix project compiling.

For what it's worth though, Docker is nothing like a VM - it really doesn't have that much overhead as long as you are running it on a linux machine. -- see https://stackoverflow.com/questions/21889053/what-is-the-runtime-performance-cost-of-a-docker-container

Duplicate of #24

**Closed as completed by hiett** 2024-05-14 03:12 UTC

**Comment by niks3089** [comment] 2024-05-14 03:26
I see, thanks for the quick response. Is there any benchmarking done to know how many requests SRH can handle? We're looking at over 10k to 100k requests per second.

**Comment by hiett** [comment] 2024-05-14 03:39
I haven't ran any benchmarks, but Elixir (especially Cowboy, the server I am using) is known to do a really good job at high throughput. I'd personally recommend you set the max_connections to a high value (that will be the thing that holds you back, as you don't want the pooler waiting for a connection), and horizontally scale to a few nodes. The more threads you can give the machine, the better the results.

I'd also recommend you run KeyDB over Redis -- it's a multi-threaded fork, which, depending on your access pattern, can get some good gains there too

**Comment by hiett** [comment] 2024-05-14 03:40
At this level of throughput requirement though, is there any reason this has to be done via HTTP? You would ultimately get better results if you can sustain your own real Redis connections.

**Comment by niks3089** [comment] 2024-05-14 03:43
I need to connect to the redis and get this throughput via cloudflare workers and they don't support direct TCP connections to redis
